var nameArray = ['Arsenal', 'Aston Villa', 'Barnsley', 'Birmingham', 'Blackburn',
    'Blackpool', 'Bolton', 'Bournemouth', 'Bradford', 'Brighton', 'Burnley',
    'Cardiff', 'Charlton', 'Chelsea', 'Coventry', 'Crystal Palace',
    'Derby', 'Everton', 'Fulham', 'Huddersfield', 'Hull', 'Ipswich', 'Leeds',
    'Leicester', 'Liverpool', 'Man City', 'Man United',
    'Middlesbrough', 'Newcastle', 'Norwich', "Nottingham Forest", 'Oldham',
    'Portsmouth', 'QPR', 'Reading', 'Sheffield United',
    'Sheffield Weds', 'Southampton', 'Stoke', 'Sunderland', 'Swansea',
    'Swindon', 'Tottenham', 'Watford', 'West Brom', 'West Ham', 'Wigan',
    'Wimbledon', 'Wolves'];
